package br.com.janaina.estudando.testesParametrizados; 

public enum EnumOperacaoEfetuada {
	PAGAMENTO_DEPOSITO_EFETUADO,
	PAGAMENTO_PIX_EFETUADO,
	PAGAMENTO_BOLETO_EFETUADO,
	PAGAMENTO_CHEQUE_EFETUADO,
	PAGAMENTO_DINHEIRO_EFETUADO,
	PAGAMENTO_CARTAO_DEBITO_EFETUADO,
	PAGAMENTO_CARTAO_CREDITO_EFETUADO,
	ERRO
}
